#!/bin/bash
declare -i a=3

if [[ $a -gt 4 ]]; then
    echo  "$a is greater than 4."
else
    echo "$a is less than 4."
fi

echo;

if (($a > 4)); then
    echo  "$a is greater than 4."
elif (($a > 2)); then
    echo "$a is greater than 2."
else
    echo "$a is less than 4."
fi