#!/usr/bin/env bash

underlinered="\033[4;31;40m"
red="\033[31;40m"
none="\033[0m"

echo -e $underlinered"ERROR:$none$red" Something went Wrong."$none"

#Use printf
printf "The results are: %d and %d\n" $((2+2)) $((5*2))

#Use echo
echo "The results are: $((2+2)) and $((5*2))"

#Formarting Data
echo  "----10----| --5--"

echo "Right aligned text and digits"
printf "%10s: %5d\n" "A Label" 123 "B Label" 456

echo "Left aligned text and Right aligned digits"
printf "%-10s: %5d\n" "A Label" 123 "B Label" 456

echo "Left aligned text and digits"
printf "%-10s: %-5d\n" "A Label" 123 "B Label" 456

echo "Left aligned text and Right aligned and padded digits"
printf "%-10s: %5d\n" "A Label" 123 "B Label" 456

echo  "----10----| --5--"

# Date Formating
echo; echo "THE DATE FORMAT"
printf "%(%Y-%m-%d %H:%M:%S)T\n" 1279994448
printf "%(%Y-%m-%d %H:%M:%S)T\n" $(date +%s)
printf "%(%Y-%m-%d %H:%M:%S)T is %s\n" -1 "the  time"